name: DockerBuild
on:
  push:
    branches: 
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: |
        yarn
        yarn build
        yarn webpack
    
    - uses: actions/upload-artifact@v1
      with:
        name: judge.js
        path: dist/judge.js
    - uses: actions/upload-artifact@v1
      with:
        name: entrypoint.js
        path: dist/entrypoint.js
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
